name: scrap3

on:
  schedule:
    - cron: '*/30 * * * *' # Schedule: every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Install the Python version needed
        
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install webdriver_manager
        
      - name: Execute Python script
        run: python data/data.py # Replace with the path to your script
        
      - name: Commit files
        run: |
          git config --local user.email "nguyenminhloc2905@gmail.com"
          git config --local user.name "minhloc29"
          git add -A
          git commit -m "update data" -a || echo "No changes to commit"
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
